# A journey of 1,000 lines starts with a single char
donate:
  - "Besides everything, we accept voluntary donations that do not enhance your gameplay in any way, but help us run the server, and we really appreciate it."
  - "Server owner: Name Surname"
  - "E-mail: mail@example.com"
  - "Donate to: Name Surname"
  - "IBAN: AA 0000000000000 00000000000000"
