main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: "1.16"
author: "Dmitriy Naumov"
description: "All in one, all in one..."
commands:
  stats:
    description: "View own stats"
    usage: "/stats"
  book:
    description: "Various manipulations with enchanted books"
    usage: "/book <dupe|upgrade>"
  gamble:
    description: "Babe, just one more command, just one more feature..."
    usage: "/gamble"
  kit:
    description: "Kits are a toolset for getting up from the bottom"
    usage: "/kit [kit name]"
  kits:
    description: "Get list of known kit names"
    usage: "/kits"
  tpa:
    description: "Teleport to other players"
    usage: "/tpa <player name>"
  back:
    description: "Go to previous location before teleporting. Not counting teleportations to spawn point after death."
    usage: "/back"
  death:
    description: "Go to last death location"
    usage: "/death"
  sethome:
    description: "Create new home"
    usage: "/sethome <home name>"
  unsethome:
    description: "Remove existing home"
    usage: "/unsethome <home name>"
  home:
    description: "Teleport to player's home"
    usage: "/home <home name> | /home <player name> <home name>"
  homeinfo:
    description: "Get info about player's home"
    usage: "/homeinfo <home name> | /homeinfo <player name> <home name>"
  homes:
    description: "Get list of homes"
    usage: "/homes"
  sharehome:
    description: "Make this home available to other players"
    usage: "/sharehome <home name> <player name | *>"
  unsharehome:
    description: "Make this home unavailable to other players"
    usage: "/unsharehome <home name> <player name | * | **>"
  busy:
    description: "Set your busy status or get one of other player"  
    usage: "/busy [player name]"
  afk:  
    description: "Set your AFK status or get one of other player"
    usage: "/afk [player name]"
  donate:
    description: "Get info about how to donate"
    usage: "/donate"
permissions:
  stats:
    description: "Permission to use /stats command"
    default: true
  book:
    description: "Permission to use /book command"
    default: true
  gamble:
    description: "Permission to use /gamble command"
    default: true
  kit:
    description: "Permission to use /kit command"
    default: true
  kits:
    description: "Permission to use /kit command"
    default: true
  tpa:
    description: "Permission to use /tpa command"
    default: true
  back:
    description: "Permission to use /back command"
    default: true
  death:
    description: "Permission to use /death command"
    default: true
  sethome:
    description: "Permission to use /sethome command"
    default: true
  unsethome:
    description: "Permission to use /unsethome command"
    default: true
  sharehome:
    description: "Permission to use /sharehome command"
    default: true
  unsharehome:
    description: "Permission to use /unsharehome command"
    default: true
  home:
    description: "Permission to use /home command"
    default: true
  homeinfo:
    description: "Permission to use /homeinfo command"
    default: true
  homes:
    description: "Permission to use /homes command"
    default: true
  busy:  
    description: "Permission to use /busy command"
    default: true
  afk:
    description: "Permission to use /afk command"
    default: true
  donate: 
    description: "Permission to use /donate command"
    default: true  
