main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: "1.16"
author: "Dmitriy Naumov"
description: "All in one, all in one..."
commands:
  dpstats:
    description: "View own stats"
    usage: "/dpstats"
permissions:
  dpstats:
    description: "Permission to use /dpstats command"
    default: true
